# Generated by Django 3.2.8 on 2023-03-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
